### ISSUE TITLE
Bath: design a "nice" space

### ISSUE THREAD

**Issue by msimerson** [The-Mountaineers/Stevens-Lodge#2]
### Design References
- Code:
    - IBC [Chapter 3, Residential](https://codes.iccsafe.org/content/IBC2018P6/chapter-3-occupancy-classification-and-use#IBC2018P6_Ch03_Sec310)
    - IBC [Chapter 11, Accessibliity](https://codes.iccsafe.org/content/IBC2018/chapter-11-accessibility#IBC2018_Ch11_Sec1109)
    - IBC [Chapter 29 Plumbing Systems](https://codes.iccsafe.org/content/IBC2018P6/chapter-29-plumbing-systems)
    - Access-Board.gov, [Guide to ADA Accessibility Standards](https://www.access-board.gov/ada/guides/chapter-6-toilet-rooms/), [Accessible Toilet Rooms](https://www.access-board.gov/ada/guides/animations/accessible-toilet-rooms.html)
    - [UPC 2018 / Seattle Plumbing Code](https://up.codes/viewer/seattle/upc-2018/chapter/3/general-regulations#3)
    - [WA Uniform Plumbing Code](https://up.codes/viewer/washington/upc-2018)
        - 02.5 Setting. Fixtures shall be set level and in proper alignment with reference to adjacent walls. No water closet or bidet shall be set closer than fifteen (15) inches (381 mm) from its center to any side wall or obstruction nor closer than thirty (30) inches (762 mm) center to center to any similar fixture. The clear space in front of any water closet or bidet shall be not less than twenty-four (24) inches (610 mm). No urinal shall be set closer than twelve (12) inches (305 mm) from its center to any side wall or partition nor closer than twenty-four (24) inches (610 mm) center to center.
        - 418.3 Location of Floor Drains. Floor drains shall be installed in the following areas:  1. Toilet rooms containing two (2) or more water closets or a combination of one (1) water closet and one (1) urinal, except in a dwelling unit. The floor shall slope toward the floor drains.  2. Laundry rooms in commercial buildings and common laundry facilities in multifamily dwelling buildings.
- parcel #: 1426139001, R-2 Dormitory zoning
- The back corner stall will be ADA / family / assisted-use.
- Others stalls will be 30” wide

#### Layout D

- It fits everything from Layout C, just rearranged.
- the "wall of stalls" has very nice symmetry
- the stalls are 1" wider and 9" deeper (standard "minimum" depth)
    - room to walk in and close the door without straddling the toilet

#### Layout C

- unisex layout
- enclosed stalls for privacy
    - stalls have same depth (51") and are 3" wider than A & B
- two extra-wide dual-use shower stalls
    - urinal in dual-use stall increases space for sinks
- walk way between stalls is sufficient (36") to comfortably pass
    - doors can open into stalls or into passage. Pros and cons both ways.
- sinks along interior wall
    - warmer pipes
    - stud bays provide a chase to hide the plumbing
    - provides an obvious place for mirrors (vs island)
    - 5 sinks / lavatories required
- spacious loitering area
    - combined with adjacent passage, makes it feel even more spacious
    - could have an island seat with toiletry cubbies beneath
- large storage cabinet
    - upper shelves for "keep away from children" items
    - middle shelves for frequently accessed personal items / toiletry cubbies
    - lower for mop bucket, supplies, potential site of a mini washer

There are tradeoffs that can be twiddled:

- the stalls could be deeper, at the cost of a narrower passage
- the stalls can be wider, at the cost of sink and cabinet space
- cabinet can be deeper without cramping the space
- toilets can hug a stall wall, to increase walkable space (see Layout C, interior wall)

#### Layouts A & B

- better than existing
- passages remain very snug
- the stall doors are impracticably close to the toilets. There's barely room to maneuver.
- space which could make the stalls nicer is consumed by passages
- the third lady has the same lack-of-privacy as today
- a single shower stall is sufficient, most of the time.
- shower has no elbow room
- the least used thing (shower) is in the way
- the shower is cramping the adjacent hallway

**Comment by msimerson** [comment]
# Layout A

2017 - by 2812 Architecture

<img width="604" alt="Stevens RR A" src="https://user-images.githubusercontent.com/261635/160031656-6349dbed-edc5-4a11-b58a-b96eaeb680b8.png">

# Layout B

2017 - by 2812 Architecture

<img width="845" alt="Stevens RR B" src="https://user-images.githubusercontent.com/261635/160031705-ea80ffbc-e408-431f-bf63-2fadb28c5949.png">

# Layout C

2022-03-08 by Matt, Derek, Jeff, Rich

<img width="1474" alt="Stevens RR C" src="https://user-images.githubusercontent.com/261635/160031715-356bc82f-c1bd-4b04-a450-a39c5f032874.png">

# Layout D

2022-03-08 by Matt

<img width="1447" alt="image" src="https://user-images.githubusercontent.com/261635/160031835-72783822-b02f-4f7c-902b-ffcb1573b849.png">

**Comment by msimerson** [comment]
Tom had a great suggestion, which was to check in with [Town Hall Seattle](https://townhallseattle.org/) and inquire about the public's reception to their gender neutral bathrooms installed a few years ago. I called today and talked with Sasha, who is the Manager of Patron Services. She said the bathrooms have been very well received. At first a few people (long time members) were confused by the change, but nobody has complained. She sent me a [link to the floor plans](https://townhallseattleorg-my.sharepoint.com/:b:/g/personal/dana_feder_townhallseattle_org/EZrIKBgLnopJnj2yB6bMWy4Bi8pA4dmGzC8GXzEmVFHgMg) and I've attached an image of just their bathrooms.

I notice in the layout that the ratio of sinks to toilets is about half. That's a data point that suggests 3 faucets will be sufficient at Stevens.

Sasha also pointed out that the demographic of Town Hall skews older, and she recommended that we also check in with Optimism Brewing, who also has gender neutral bathrooms. I wasn't able to reach them via phone but Optimism is so proud of their bathrooms they warrant a section describing them [on their web site](https://optimismbrewing.com/visit/beer-hall) AND in their [FAQ](https://optimismbrewing.com/faq)!

> FRIENDLY BATHROOMS
> 
> Our bathrooms are awesome.  Bathrooms don't usually make the website, but ours are so awesome we think they are worth the visit.  All-gender bathrooms are the best use of resources because they make all fixtures available to all visitors instead of arbitrarily segregating by gender.  Individual rooms for everyone are more private and comfortable.  It is easier for parents to accompany their opposite gender kids to the restroom when all genders are together.  No one can discriminate as to whether someone is using the ‘correct’ gender-segregated bathroom.  Unisex is just safer.
> 
>
>Plus, when everyone is watching, we believe that more people wash their hands.

**Comment by msimerson** [comment]
# Layout E 0.5

2022-03-16 by Derek

![image0](https://user-images.githubusercontent.com/261635/160033007-2d8de442-a2aa-4f8c-94db-9131754ce546.jpeg)

# Layout E

- the urinal is the highest traffic stall, moving it forward makes sense
- the large shower / toilet / changing stall is nice. Great idea.
- we can use a shared drain channel for both showers?
- the showers have valves and extra plumbing in the walls.
    - putting them on the inside wall makes them less prone to freezing
    - IIRC, that inside wall backs up to the stairs, improving access to the shower plumbing
- a toilet is a big toe stubbing fixture in the shower space
    - toilet seats aren't perceived as "nicer" after getting sprinkled with shower water
- urinals, and the floor under them, are nicer after getting sprinkled with shower water
    - putting the urinal in a shower stall makes "freshening up" easier
    - especially if the shower has a wand
 
<img width="1594" alt="Screen Shot 2022-03-21 at 11 35 52 AM" src="https://user-images.githubusercontent.com/261635/160033044-6e406367-c853-47cb-80b2-bbdb92f1bb92.png">

# Layout F

- imagine how much fun it would be to tear into the beautifully finished wall to repair a broken shower valve, versus being able to open a small door on the back side of the wall and have full access
- the shower inlets are closer to the hot water supply, so less running water down the drain waiting for warmth
- If we swing the fourth stall around onto the outside wall, the second shower stall can grow wider. Wide enough that it matters much less if a toilet or urinal goes in there. If we put the urinal in there, then the stall can also be less deep (moving as far back as the drain). If a toilet goes in there, it could be wide enough for a shower curtain to keep the toilet dry. 

<img width="1586" alt="Screen Shot 2022-03-21 at 5 36 07 PM" src="https://user-images.githubusercontent.com/261635/160033222-f38c6f71-b5d6-4baa-b033-2e07e0a46c4c.png">

> These are great plans! I like the idea of putting a urinal in a shower, sharing a drain, and putting the shower heads on the same interior wall. Jason, Jeff, and I will meet next week to finalize a bathroom plan. -- Derek

**Comment by msimerson** [comment]
> Good afternoon All,
>
> We have a finalized bathroom floor-plan for Stevens Lodge! Many thanks to all for your help with the iterations. 
>
> Here are the specifics:
>
> The space is roughly 12ft x 18ft. It will have two shower stalls. One 4ft x 5ft and one 4ft x 7ft. Both will be wet rooms with floor drains. These spaces will double as private changing areas. 
> 
> There will be 5 toilet stalls with dimensions of roughly 3ft x 5ft. Four of the stalls will have seated toilets and the one closest to the entrance will have a urinal.
> 
> The sink will  be a trough with three faucets and occupy a space of roughly 2ft  x 6ft. Next to the sink we will have floor to ceiling storage that will be 2ft x 5ft x 8ft.
> 
> We want a central floor drain so that the entire space can be washed down. 

![image0](https://user-images.githubusercontent.com/261635/160971909-ba6cee4e-0ec8-464f-be6c-a3ce78191412.jpg)

**Comment by msimerson** [comment]
Yahoo, progress!  I like the layout. Now it's time to iron out some important details.

I have 11' 6" as the finished interior space. Figure that after demoing everything back to the studs, we're going to then cover the studs with wallboard (or plywood), and then affix wall tiles over that, all of which consume some of the interior space.

The same goes for the length. I'm using 17' 8" for the finished interior dimension. The stall walls will eat up some physical space, I'm using 1" for now (Rich?). Standard toilet stall dimensions are 36" wide. I shrank the finished widths to 34", which leaves 37" for the shower stall width. If there is a a few extra inches in that space, we could use it to make the toilet stalls each a tiny bit wider, or give it all to the shower stall?

Shown are standard 2' wide stall doors.

We can't put the shower valve and head on a stall wall between the shower and the toilet stall. The shower mixing valve is a big thick hunk of brass and it needs a "normal" wall depth to hide inside. The choice is then, move the shower head (shown), or spend another 5" of that precious 18' to build in a partition wall, making the toilets and shower stalls that much narrower.


<img width="1865" alt="Screen Shot 2022-03-30 at 8 01 09 PM" src="https://user-images.githubusercontent.com/261635/160972242-111ac15d-f293-4f08-9249-18e721cfe44e.png">

[Stevens Bath G.skp.zip](https://github.com/The-Mountaineers/Stevens-Lodge/files/8385811/Stevens.Bath.G.skp.zip)

**Comment by JeffB-Mountaineers** [comment]
We can have another foot on the stall side. See the attached that shows the odd angled wall that’s part of our bathroom walls and entrance. We’d need to keep the storage/sink side at ~18 ft, but can push out to ~19 feet on the stall side. We were thinking that squaring off the bathroom made sense, but if it means narrower stalls, then may not be the best ides. 😊

Using 11’6” for the width is a-ok. With this configuration we’ll have a wide “hallway” in the middle of the bathroom.

The back-to-back shower configuration makes sense—more space per stall. I assume we can/will offset the mixing valves to minimize wall thickness?

I think we want to keep the shower width as close to 4 ft (48 in) as possible, probably no less than 42 in. Hopefully we can do that with that extra foot on the stall side.

![Bathroom Rough Dimensions](https://user-images.githubusercontent.com/4585029/161068894-06bc75e2-862a-43b4-8137-b6dbf40e7e78.jpg)

**Comment by JeffB-Mountaineers** [comment]
[from Matt] 

> We can have another foot on the stall side. See the attached that shows the odd angled wall that’s part of our bathroom walls and entrance. We’d need to keep the storage/sink side at ~18 ft, but can push out to ~19 feet on the stall side. We were thinking that squaring off the bathroom made sense, but if it means narrower stalls, then may not be the best ides. 😊 

That could work. Per my math, 5 toilets + 1 shower = 6 stalls * 3' each = 18'. But if you've got another foot, then having a 4'  shower stall is definitely nicer.

Something to keep in mind is that to get a central drain, we need to put in a slab floor (so we can pour it in place and slope the floors to the drain). The minimum slab thickness is 2", at the lowest point (the central drain). From the central drain the floor tapers up to the outside edges. That means there's going to be a step "up" onto the bathroom floor, and the outside edge will be the thickest part.

Also, because we're pouring the slab over a flexible building material (wooden floor on wooden beams), we need to beef up the floor so that our slab doesn't crack. At a minimum, a second 3/4" plywood subfloor (1.5"), then an waterproof uncoupling membrane[1], and then the minimum 2" of concrete. That's a minimum floor thickness of about 4", and that's predicated on insulating the floor beneath the subfloor with spray foam, which will also help stiffen up the floor.

I'm telling you all that to help you decide if you want to extend the bathrooms that extra foot.

> The back-to-back shower configuration makes sense—more space per stall. I assume we can/will offset the mixing valves to minimize wall thickness?

Exactly, and a standard 3.5" wall is shown (but probably not visible in the screen shots). I had a conversation with our plumber guy and we decided that the mixing valve on the toilet stall side should be closer to the outside wall (and further from the shower door, and "harms way"), whereas the mixing valve on the other side of the wall can be nearer the interior partition wall. Most people choose to stand out from under the shower when turning on the shower anyway, so I don't think it's a problem to have the shower head centered while the handles are offset.

For maintenance, we can put in an access panel behind each valve that gets caulked in place. When the mixing valves need maintenance in 20+ years (we hope), the plumber needs only to cut out the caulk, pull the access panel out, and voila, easy access and a minor project instead of a major one. I call that, "leaving little love notes for the future."

**Comment by JeffB-Mountaineers** [comment]
I’m wondering about two things…

1. The larger shower and toilet stall in the back corner and very close and I am worried about ingress/egress issues with the doors being so close. Maybe we should swap the showers and combine the shower and toilet in the back corner. That makes all of the showers and stalls a fair bit more spacious. See the attached for a rough, not-quite-to-scale drawing. It shows the shower swap and shower/toilet combo, and the extra foot we have on the stall side.

2. I am worried about having to step up to enter the bathroom. How do we ameliorate that issue? Skip having a central drain? Build up the hallway and add sloping up and down the hallway so that there’s no big lip that requires stepping up?

**Comment by msimerson** [comment]
From my April 4th email reply:

> Based on the descriptions of usage when Rich and I were there (toilet usage primarily in ski season, shower use predominantly during summer / hiker season), making one a combination stall seems like a very workable solution. As you say, the stalls can all get a little wider, the shower / changing rooms both get a nice space boost, and there's no need for that extra foot of space in the walkway.
>
> There's a variety of potential solutions:
>
>	1. sloping in the hallway has potential. My concern there will be how to manage the height difference with the outside door in that hallway. 
>	2. make it a "full" step height of 4". Paint two stair treads (bright yellow is commonly used for this purpose) on the floor so the step visually stands out. Affix low level lighting in the vertical portion so that the step catches the eye when walking to and from the area. Potentially, add a stub wall along the storage closet that "encloses" the bathroom space down to a 36" doorway, so that we're walking into a doorway, with a threshold, and where a small step up wouldn't be a surprise.
>	3.  choose a different flooring material. The critical factors to consider in a public bathroom are: water resistance, durability, safety, health / sanitation, and cost.
>
> Material Choices
>
>	- Concrete is the standard because the materials are cheap (the labor, less so), it's highly durable, and it's super easy to clean and to maintain. It can be stained, textured, etched, epoxy coated, etc, so the appearance is highly versatile.
>	- Tile: also very durable, also requires a very stiff / strong backing to avoid cracking. Compared to concrete, it has a thinner profile, has group seams, which are less easy to clean and also need regular cleaning and sealing. Tile is more labor intensive, costs more to install, but also looks and feels very nice.
>	- Premium vinyl: available in a huge array of patterns, it looks good and wears good, for about 10 years. Before 20 years, plan to tear it up and replace it. I've seen a lot more public restrooms with this in the past few years, including in hotel, restaurant, and gas station baths. Will it wear better than the vinyl flooring of yesteryear? Ask me again in 15 years. ;-)
>
>A big downsize to going with a sheet material like vinyl or linoleum is that in order to "fix" it, you need to remove all the stalls and toilets, pull the sheet material up, and then replace. Vinyl now comes in "tiles," but none of the contractors I asked have any experience installing, repairing, or maintaining them.
>
>So many fun little things to think about!

**Comment by JeffB-Mountaineers** [comment]
What about microcement?

**Comment by msimerson** [comment]
And how exactly does a 2-3mm application thickness of microcement generate the slope necessary for an effective central drain?

**Comment by JeffB-Mountaineers** [comment]
The same as tile or vinyl?

**Comment by msimerson** [comment]
<img width="1757" alt="Screen Shot 2022-04-23 at 9 02 15 PM" src="https://user-images.githubusercontent.com/261635/164956039-8b808318-03a6-49cf-90e5-5faf6284a265.png">

**Comment by JeffB-Mountaineers** [comment]
![Stevens Lodge Gender Neutral Bathroom Floor Plan](https://user-images.githubusercontent.com/4585029/165004693-43c30511-c586-4e2b-b5e1-286c62c94219.jpg)

**Comment by msimerson** [comment]
After consultation with a professional architect and King County Public Health, a few revisions have been made. We do need all 5 toilets + 1 urinal and we need a an assisted use / family / accessibility stall. 

<img width="1934" alt="Layout G, aerial" src="https://user-images.githubusercontent.com/261635/167035148-2deb54e5-3e6e-4813-981d-0d99d8421f46.png">
<img width="1662" alt="Layout G, front" src="https://user-images.githubusercontent.com/261635/167035152-caa4d8aa-06d7-4a78-960b-084b84fd0bb5.png">

**Comment by msimerson** [comment]
# Mostly Installed

![IMG_4313](https://user-images.githubusercontent.com/261635/217366374-32116705-4740-4e98-90b8-75ca1dd44796.jpeg)
![IMG_4316](https://user-images.githubusercontent.com/261635/217366389-b9a437c4-0f1b-4e9d-9753-866b28722eb4.jpeg)
![IMG_4318](https://user-images.githubusercontent.com/261635/217366424-4dae3922-7989-459c-bcf3-79a029a8ec1e.jpeg)
